server:
  port: 8086
  forward-headers-strategy: framework
spring:
  cloud:
    gateway:
      routes:
        - id: publication-service-route
          uri: lb://publication-service
          predicates:
            - Host=publication.api.vk.spring24v1.172.28.160.1.nip.io
        - id: feedback-service-route
          uri: lb://feedback-service
          predicates:
            - Host=feedback.api.vk.spring24v1.172.28.160.1.nip.io
        - id: messenger-service-route
          uri: lb://messenger-service
          predicates:
            - Host=messenger.api.vk.spring24v1.172.28.160.1.nip.io
        - id: message-service-route
          uri: lb://message-service
          predicates:
            - Host=message.api.vk.spring24v1.172.28.160.1.nip.io
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/vk-spring24v1
        registration:
          discovery:
            provider: keycloak
            client-id: api-gateway
            client-secret: C5gLeTTwZWzdKFSTHAR8dslXj0lM9lXC
            authorization-grant-type: client_credentials
            scope:
              - discovery
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    enabled: true
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 1
