server:
  port: 8086
  forward-headers-strategy: framework
spring:
  application:
    name: api-gateway
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@172.28.160.1:8888