spring:
  application:
    name: publication-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://localhost:8888
      password: config-password
      username: config
server:
  port: 8081
  forward-headers-strategy: framework