server:
  port: 8084
  forward-headers-strategy: framework
spring:
  jpa:
    show-sql: true
  application:
    name: messenger-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://172.28.160.1:8888
      username: config
      password: config-password