server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: eureka-server
            client-secret: te7lbHeqIaIQNglItMVPATmD0Qon1KKY
            scope:
              - openid
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:8082/realms/vk-spring24v1
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/vk-spring24v1