spring:
  application:
    name: feedback-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://172.28.160.1:8888
      username: config
      password: config-password
server:
  port: 8083
  forward-headers-strategy: framework